### ISSUE TITLE
Differentiate block code styling from inline code

### ISSUE THREAD

**Issue by siamaksade** [openshift-roadshow/cloud-native-katacoda#15]
Currently, inline code and block code have the same styling. It would be more readable to distinguish between the two for example:

<img width="482" alt="screen shot 2017-10-27 at 14 04 01" src="https://user-images.githubusercontent.com/1174934/32103217-b7cd2866-bb1f-11e7-8db9-1e95c7cc2098.png">

The above example uses this style:

```css
p > code {
    background: transparent !important;
    color: #9e040b !important;
    font-size: 14px !important;
}
```

Any font color is fine as long is it's different from block code.
